Update phalcon

diff --git a/support/build/extensions/no-debug-non-zts-20121212/phalcon b/support/build/extensions/no-debug-non-zts-20121212/phalcon
--- a/support/build/extensions/no-debug-non-zts-20121212/phalcon
+++ b/support/build/extensions/no-debug-non-zts-20121212/phalcon
@@ -1,1 +1,30 @@
-nice
+#!/usr/bin/env bash
+# Build Path: /app/.heroku/php/
+# Build Deps: php-5.5.11
+
+OUT_PREFIX=$1
+
+# fail hard
+set -o pipefail
+# fail harder
+set -eux
+dep_dirname=phalcon
+dep_url=git://github.com/phalcon/cphalcon.git
+
+echo "-----> Building Phalcon"
+
+git clone --depth=1 ${dep_url} 
+
+pushd ${dep_dirname}
+export PATH=${OUT_PREFIX}/bin:${PATH}
+phpize
+./configure \
+    --prefix=${OUT_PREFIX} \
+    --enable-phalcon
+make -s -j 9
+# php was a build dep, and it's in $OUT_PREFIX. nuke that, then make install so all we're left with is the extension
+rm -rf ${OUT_PREFIX}/*
+make install -s
+popd
+
+echo "-----> Done."
